name: Run Unittests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittests
      run: |
        python -m unittest discover -s tests
    
    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/test-results.xmlame